title: GitHub Training Log
author: luisoliveiras
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  My GitHub training log.

# social links
twitter_username: luis_oliveiras # DO NOT include the @ character, or else the build will fail!
github_username:  luisoliveiras # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
theme: minima
